#!/usr/bin/env bash

name=""
branch=""
args=()
positionals=()

while [[ $# -gt 0 ]]; do
    case $1 in
        -n|--name)
            name="$2"
            shift 2
            ;;
        -r|--branch)
            branch="$2"
            shift 2
            ;;
        -b)
            args+=('-b')
            shift 1
            ;;
        *)
            positionals+=("$1")
            shift
            ;;
    esac
done

: "${name:=${positionals[0]:?'err: name required (-n/--name)'}}" "${branch:=${positionals[1]:=${name:?'err: branch required (-b/--branch)'}}}"

git worktree add \
  --relative-paths \
  "${name}" \
  "${args[@]}" \
  "${branch}"
