#!/usr/bin/env bash
set -euo pipefail

repo=""
name=""
positionals=()

while [[ $# -gt 0 ]]; do
    case $1 in
        -r|--repo)
            repo="$2"
            shift 2
            ;;
        -n|--name)
            name="$2"
            shift 2
            ;;
        *)
            positionals+=("$1")
            shift
            ;;
    esac
done

: "${repo:=${positionals[0]?'err: repo required (-r/--repo)'}}" "${name:=${positionals[1]?'err: name required (-n/--name)'}}"

git clone --bare "${repo}" "${name}.git"

pushd "${name}.git"
git config --local --add remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch
popd
