#!/usr/bin/env bash

repo=""
name=""
positionals=()

while [[ $# -gt 0 ]]; do
    case $1 in
        -r|--repo)
            repo="$2"
            shift 2
            ;;
        -n|--name)
            name="$2"
            shift 2
            ;;
        *)
            positionals+=("$1")
            shift
            ;;
    esac
done

: "${repo:=${positionals[0]?'err: repo required (-r/--repo)'}}" "${name:=${positionals[1]:=$(basename $(pwd))}}"

git clone "${repo}" "${name}.git"
echo "gitdir: ./${name}.git/.git" > .git

pushd "${name}.git" >/dev/null
git checkout $(git commit-tree $(git hash-object -t tree /dev/null) < /dev/null) &>/dev/null
popd >/dev/null
