#!/usr/bin/env bash
set -euo pipefail

repo=""
name=""
positionals=()

while [[ $# -gt 0 ]]; do
    case $1 in
        -r|--repo)
            repo="$2"
            shift 2
            ;;
        -n|--name)
            name="$2"
            shift 2
            ;;
        *)
            positionals+=("$1")
            shift
            ;;
    esac
done

repo=${repo:-${positionals[0}}
name=${name:-${positionals[1}}

if [[ -z "${repo}" ]]; then
  echo "err: repo required (-r/--repo)" >&2
  exit 1
fi
if [[ -z "${name}" ]]; then
  echo "err: name required (-n/--name)" >&2
  exit 1
fi

git clone --bare "${repo}" "${name}.git"

pushd
git config --local --add remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch
popd
