#!/usr/bin/env bash

name=""
positionals=()

while [[ $# -gt 0 ]]; do
    case $1 in
        -n|--name)
            name="$2"
            shift 2
            ;;
        *)
            positionals+=("$1")
            shift
            ;;
    esac
done

: "${name:=${positionals[0]:?'err: name required (-n/--name)'}}"

git worktree remove "${name}"
