#!/usr/bin/env bash
# sarsoo: summary="Diff helm outputs"
# sarsoo: visibility="public"
set -uo pipefail

usage() {
  cat <<'EOF'
Usage: so htd [options] [positionals]

Diff an existing helm templated output with the output from a working directory

Options:
  -b, --base DIR        Directory of existing templates to diff against
  -d, --dir DIR         Chart directory (default: .)
  -o, --output-dir DIR  Directory to output --dir templates to (default: ./templated)
  -h, --help            Show this help
EOF
}

for arg in "$@"; do
  case "$arg" in
    -h|--help)
      usage
      exit 0
      ;;
  esac
done

lhs_dir=""
rhs_dir="$(pwd)"
rhs_output_dir=""
positionals=()

while [[ $# -gt 0 ]]; do
    case $1 in
        -d|--dir)
            rhs_dir="$2"
            shift 2
            ;;
        -o|--output-dir)
            rhs_output_dir="$2"
            shift 2
            ;;
        -b|--base)
            lhs_dir="$2"
            shift 2
            ;;
        *)
            positionals+=("$1")
            shift
            ;;
    esac
done

: "${lhs_dir:?'err: --base/-b is required to diff against'}" "${rhs_output_dir:=${rhs_dir}/templated}"

so ht \
    --output-dir "${rhs_output_dir}" \
    --chart "${rhs_dir}" \
    "${positionals[@]}"  >/dev/null

if [[ $? != 0 ]]; then
    echo "err: failed to template helm" >&2
    exit 1
fi

[[ -t 1 ]] && output_colour='always' || output_colour='never'

diff_output=$(diff \
    --recursive \
    -u \
    --suppress-common-lines \
    --ignore-file-name-case \
    --color="${output_colour}" \
    "${lhs_dir}" "${rhs_output_dir}")

if [[ $? == 2 ]]; then
    echo "err: diff failed" >&2
    exit 1
fi

if [[ -t 1 ]]; then
  echo "${diff_output}" | ${PAGER:-less -R}
else
  echo "${diff_output}"
fi
