#!/usr/bin/env bash

file=""
sed=""

while [[ $# -gt 0 ]]; do
    case $1 in
        -f|--file)
            file="$2"
            shift 2
            ;;
        -s|--sed)
            sed="$2"
            shift 2
            ;;
    esac
done

[[ -z "${file}" ]] && exit 1;
[[ -z "${sed}" ]] && exit 1;

find . -type f -name "${file}" -print0 | xargs -0 sed -i "${sed}"
