#!/usr/bin/env bash

file=""
sed=""

while [[ $# -gt 0 ]]; do
    case $1 in
        -f|--file)
            file="$2"
            shift 2
            ;;
        -s|--sed)
            sed="$2"
            shift 2
            ;;
    esac
done

: "${file:?}" "${sed:?}"

case "$(uname -s)" in
    Darwin*)    machine=Mac;;
    *)          machine="UNKNOWN:${unameOut}"
esac

if [[ "${machine}" == "Mac" ]] then;
  find . -type f -name "${file}" -print0 | xargs -0 sed -i '' "${sed}"
else
  find . -type f -name "${file}" -print0 | xargs -0 sed -i "${sed}"
fi
