#!/usr/bin/env bash
# sarsoo: summary="Kill remote dev servers"
# sarsoo: visibility="public"

cmds=(code goland embeddings rider pycharm jetbrains)
for i in "${cmds[@]}"; do
  pgrep -la $i
  pkill -9 $i
done
