#!/usr/bin/env bash
# sarsoo: summary="Install fresh editor"
# sarsoo: visibility="public"
set -euo pipefail

curl https://raw.githubusercontent.com/sinelaw/fresh/refs/heads/master/scripts/install.sh | sh
