#!/usr/bin/env bash
# sarsoo: summary="Install helm plugins"
# sarsoo: visibility="public"

helm plugin install https://github.com/databus23/helm-diff --verify=false &>/dev/null
# helm plugin install https://github.com/dadav/helm-schema --verify=false &>/dev/null
