#!/usr/bin/env bash

tmux_session="snd_$(date +%s)"
protocol=""
host=""
positionals=()

while [[ $# -gt 0 ]]; do
    case $1 in
        -p|--protocol)
            protocol="$2"
            shift 2
            ;;
        -h|--host)
            host="$2"
            shift 2
            ;;
        *)
            positionals+=("$1")
            shift
            ;;
    esac
done

if (( ${#positionals[@]} > 1 )); then
  echo "Unknown arguments" >&2
  exit 1
fi

host="${host:-${positionals[0]}}"

if [[ -z "${host}" ]]; then
  echo "No host provided" >&2
  exit 1
fi

if [[ -z "${protocol}" ]]; then
  proto_options=("icmp" "tcp" "udp")
  protocol=$(printf "%s\n" "${proto_options[@]}" | fzf --header "Pick a protocol....")
fi

output_path="${HOME}/snd/$(date +%Y/%m/%d/%H%M%S)_${host}"
mkdir -p "${output_path}"

tmux new -d -s "${tmux_session}"
first_window=$(tmux list-windows -t "${tmux_session}" | cut -d ':' -f1)
first_pane=$(tmux list-panes -t "${tmux_session}:${first_window}" | cut -d ':' -f1)
tmux split-window -v -t "${tmux_session}:${first_window}"
tmux split-window -h -t "${tmux_session}:${first_window}.2"



tmux send-keys -t "${tmux_session}:${first_window}.${first_pane}" "command mtr -b ${host} -e" Enter

tmux send-keys -t "${tmux_session}:${first_window}.2" "command dig ${host} | tee ${output_path}/dig.txt" Enter
tmux send-keys -t "${tmux_session}:${first_window}.3" "command ip route get ${host} | tee ${output_path}/route.txt" Enter




tmux attach -t "${tmux_session}"
