#!/usr/bin/env bash
# sarsoo: summary="Sarsoo Network Debugging"
# sarsoo: visibility="public"

usage() {
  cat <<'EOF'
Usage: so snd [options] [positionals]

Broad network debugging workspace in tmux

Options:
  -p, --protocol PROTO  (icmp/tcp/udp)
  -h, --host HOSTNAME   IP/hostname to target
  -h, --help            Show this help
EOF
}

for arg in "$@"; do
  case "$arg" in
    --help)
      usage
      exit 0
      ;;
  esac
done

tmux_session="snd_$(date +%s)"
protocol=""
host=""
positionals=()

while [[ $# -gt 0 ]]; do
    case $1 in
        -p|--protocol)
            protocol="$2"
            shift 2
            ;;
        -h|--host)
            host="$2"
            shift 2
            ;;
        *)
            positionals+=("$1")
            shift
            ;;
    esac
done

if (( ${#positionals[@]} > 1 )); then
  echo "err: Unknown arguments" >&2
  usage
  exit 1
fi

host="${host:-${positionals[0]}}"

if [[ -z "${host}" ]]; then
  echo "err: No host provided" >&2
  usage
  exit 1
fi

if [[ -z "${protocol}" ]]; then
  proto_options=("icmp" "tcp" "udp")
  protocol=$(printf "%s\n" "${proto_options[@]}" | fzf --header "Pick a protocol....")
fi

output_path="${HOME}/snd/$(date +%Y/%m/%d/%H%M%S)_${host}"
mkdir -p "${output_path}"

# -d = detached
# -s = name
# -c = start dir
# -n = window name
# -P = print session info ‘#{session_name}:’
tmux new-session -d -s "${tmux_session}"

# -a = all
# -f = filter
# -F = format
first_window=$(tmux list-windows -t "${tmux_session}" | cut -d ':' -f1)
# -a = all panes on server
# -s = target is session
first_pane=$(tmux list-panes -t "${tmux_session}:${first_window}" | cut -d ':' -f1)
# -v = vertical
# -h = horizontal
# -t = target pane
tmux split-window -v -t "${tmux_session}:${first_window}"
tmux split-window -h -t "${tmux_session}:${first_window}.2"



tmux send-keys -t "${tmux_session}:${first_window}.${first_pane}" "command mtr -b ${host} -e" Enter

tmux send-keys -t "${tmux_session}:${first_window}.2" "command dig ${host} | tee ${output_path}/dig.txt" Enter
tmux send-keys -t "${tmux_session}:${first_window}.3" "command ip route get ${host} | tee ${output_path}/route.txt" Enter


if [[ -z "${TMUX}" ]]; then
  tmux attach -t "${tmux_session}"
else
  echo "snd tmux session [${tmux_session}] started..."
fi
